#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

cp ../bin/container-crontab .

if dapper -d --build -f Dockerfile -- -t ${REPO}/container-crontab:${TAG}${SUFFIX} .; then
    echo Built ${REPO}/container-crontab:${TAG}
elif [ "$?" != "42" ]; then
    exit 1
else
    echo "Skipping ${TAG}"
    exit 0
fi

